In [1]:
import numpy as np
from scipy.sparse import csr_matrix

In [2]:
# Create a 2-D array
arr = np.array([[1,0,0],[7,3,0,],[0,5,2]])
print('Original matric:\n',arr)

Original matric:
 [[1 0 0]
 [7 3 0]
 [0 5 2]]


In [3]:
# Converting to sparse matrix
sm = csr_matrix(arr)
print(sm)

  (0, 0)	1
  (1, 0)	7
  (1, 1)	3
  (2, 1)	5
  (2, 2)	2


In [4]:
print(sm.data)

[1 7 3 5 2]


In [10]:
from scipy.sparse import csc_matrix
smc= csc_matrix(arr, shape=(3,3))
print(smc)

  (0, 0)	1
  (1, 0)	7
  (1, 1)	3
  (2, 1)	5
  (2, 2)	2


In [11]:
from scipy import stats

In [12]:
dir(stats)

['BootstrapMethod',
 'CensoredData',
 'ConstantInputWarning',
 'Covariance',
 'DegenerateDataWarning',
 'FitError',
 'MonteCarloMethod',
 'NearConstantInputWarning',
 'PermutationMethod',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_axis_nan_policy',
 '_biasedurn',
 '_binned_statistic',
 '_binomtest',
 '_boost',
 '_censored_data',
 '_common',
 '_constants',
 '_continuous_distns',
 '_covariance',
 '_crosstab',
 '_discrete_distns',
 '_distn_infrastructure',
 '_distr_params',
 '_entropy',
 '_fit',
 '_hypotests',
 '_kde',
 '_ksstats',
 '_levy_stable',
 '_mannwhitneyu',
 '_morestats',
 '_mstats_basic',
 '_mstats_extras',
 '_multicomp',
 '_multivariate',
 '_mvn',
 '_odds_ratio',
 '_page_trend_test',
 '_qmc',
 '_qmc_cy',
 '_qmvnt',
 '_rcont',
 '_relative_risk',
 '_resampling',
 '_rvs_sampling',
 '_sensitivity_analysis',
 '_sobol',
 '_statlib',
 '_stats',
 '_stats_mstats_common',
 '_stats_py',
 '_s